Blog/app/forms/auth_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import DataRequired, Length, Email, EqualTo


class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=2, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=4)])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Register')


class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Login')

Blog/app/__init__.py
from flask import Flask
from dotenv import load_dotenv
import os
from app.routes.blog import blog_route
from app.routes.auth import auth_route

load_dotenv()


def create_app():
    app = Flask(__name__)

    app.config["SECRET_KEY"] = os.getenv("SECRET_KEY")

    app.config.update(DEBUG=True, ENV="development")
    app.register_blueprint(blog_route)
    app.register_blueprint(auth_route)

    return app

Blog/app/routes/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from app.forms.auth_form import RegistrationForm, LoginForm

auth_route = Blueprint('auth_route', __name__, template_folder='templates/auth', url_prefix='/auth')


@auth_route.route('/register', methods=('GET', 'POST'))
def register():
    form = RegistrationForm()
    if request.method == 'POST' and form.validate_on_submit():
        flash(f'Account created for {form.username.data}', 'success')
        return redirect(url_for('auth_route.login'))

    return render_template('auth/register.html', form=form, title='Register')


@auth_route.route('/login', methods=('GET', 'POST'))
def login():
    form = LoginForm()
    if request.method == 'POST' and form.validate_on_submit():
        flash('You have been logged in!', 'success')
        return redirect(url_for('blog_route.index'))
    else:
        flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('auth/login.html', form=form, title='Login')


@auth_route.route('/logout')
def logout():
    pass


@auth_route.route('/reset_password', methods=('GET', 'POST'))
def reset_request():
    pass

Blog/app/routes/blog.py
from flask import Flask, render_template, request, Blueprint, url_for

blog_route = Blueprint('blog_route', __name__, template_folder='templates/blogs')

POSTS = [
    {'id': 1, 'title': 'First Blog Post','author': 'Samuel ov', 'content': 'This is the content of the first blog post.', 'date_posted': 'April 20, 2024'},
    {'id': 2, 'title': 'Second Blog Post', 'author': 'Jane Doe', 'content': 'This is the content of the second blog post.', 'date_posted': 'April 21, 2024'}
]

@blog_route.route('/')
def index():
    return render_template('blogs/index.html', posts=POSTS, title='Blog Home')

Blog/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% if title %}
    <title>{{ title }} - vxBlog</title>
    {% else %}
    <title>vxBlog</title>
    {% endif %}
    <!--    bootstrap css link-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!--    custom css link-->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
</head>
<body>
{% include 'partials/navbar.html' %}

<div class="container">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    {% for category, message in messages %}
    <div class="alert alert-{{ category }}  mt-3" role="alert">
        {{ message }}
    </div>
    {% endfor %}
    {% endif %}
    {% endwith %}
    {% block content %}
    <!--MAIN CONTENT-->
    {% endblock content %}
</div>
<!--    bootstrap js link-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
</body>
</html>

Blog/app/templates/blogs/index.html
{% extends "base.html" %}

{% block content %}
   <h1>Home Page</h1>
   {% for post in posts %}
       <div>
           <h2>{{ post.title }}</h2>
           <p>{{ post.content }}</p>
       </div>
   {% endfor %}
{% endblock content %}

Blog/app/templates/partials/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{{ url_for('blog_route.index')}}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Profile</a>
                </li>
            </ul>
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('auth_route.login')}}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{url_for('auth_route.register')}}">Register</a>
                </li>
            </ul>
        </div>
    </div>
</nav>